### ISSUE TITLE
Create an endpoint to update precinct data ((PATCH or PUT) /precincts/:precinct_id)

### ISSUE THREAD

**Issue by masonforest** [Bernie-2016/CaucusCentralAPI#4]
(PACTH or PUT) `/precincts/:precinct_id?supporting_attendees=100`

Should update the that precinct

**Comment by kyletns** [comment]
Hey it isn't merged yet, but when this is merged, just know that it's going to need the params wrapped in an object called `precinct`, so depending on which library you're using, you'd want to send the params like either this:

```
  precinct: {
    supporting_attendees: 100
  }
```

or this:

```
  precinct[supporting_attendees]=100
```

**Comment by kyletns** [comment]
@masonforest check #9 for deets!
